<?php

namespace Cultpantry\Elections\Support;

/**
 * Elections -> City Plans + Finances -> City grants: the grants the City has
 * applied for since 2016, what came of each, how much grant money arrived,
 * and how that compares with BC towns of a similar size.
 *
 * How it was built (Oct. 2026):
 *  - Applications: every council resolution authorizing a grant application,
 *    read from the City's minutes and agenda packages (AgendaCenter for
 *    2016-Aug. 2023, eScribe from Sept. 2023). Letters of support for other
 *    groups' applications are left out.
 *  - Outcomes: the grant schedule (Schedule 3 / the Government Transfers
 *    note) in each year's audited statements, funder announcements and news.
 *    "not_funded" is inferred from public evidence (a re-application, a
 *    budgeted grant that never arrived, published funding that leaves it
 *    out); "no_record" means only that no money or award was found.
 *  - Money by year: every Schedule 3 line 2016-2025, split into formula
 *    money and grants the City applied for (see the `formula` list in
 *    CityGrantsTest).
 *  - Peers: Province of BC Schedules 201 (2021 census) and 401 (federal,
 *    provincial and other-government transfers), 2015-2024.
 *
 * When adding a result, update `ledger`, then let the tests confirm the
 * headline counts still match.
 */
class CityGrants
{
    /** Key for this page in the update feed. */
    public const SLUG = 'city-grants';

    public static function sheet(): array
    {
        return [
            'title' => 'City grants',
            'subtitle' => 'What Salmon Arm has applied for since 2016, what it won, and how it compares.',
            'read_on' => '2026-10-05',

            'sources' => [
                'agendaCenter' => ['label' => 'City of Salmon Arm council minutes and agenda packages, 2016 to August 2023', 'url' => 'https://www.salmonarm.ca/AgendaCenter', 'date' => null],
                'escribe' => ['label' => 'City of Salmon Arm council minutes, September 2023 to 2026 (eScribe)', 'url' => 'https://pub-salmonarm.escribemeetings.com/', 'date' => null],
                'ar2016' => ['label' => 'City of Salmon Arm 2016 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/795', 'date' => null],
                'ar2017' => ['label' => 'City of Salmon Arm 2017 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/890', 'date' => null],
                'ar2018' => ['label' => 'City of Salmon Arm 2018 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/996', 'date' => null],
                'ar2019' => ['label' => 'City of Salmon Arm 2019 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1035', 'date' => null],
                'ar2020' => ['label' => 'City of Salmon Arm 2020 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1073', 'date' => null],
                'ar2021' => ['label' => 'City of Salmon Arm 2021 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1129', 'date' => null],
                'ar2022' => ['label' => 'City of Salmon Arm 2022 Annual Report, Schedule 3 (grants)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1168', 'date' => null],
                'fs2023' => ['label' => 'City of Salmon Arm 2023 financial statements, Note 14 (government transfers)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1219', 'date' => null],
                'fs2024' => ['label' => 'City of Salmon Arm 2024 financial statements, Note 13 (government transfers)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1275', 'date' => null],
                'fs2025' => ['label' => 'City of Salmon Arm 2025 financial statements, Note 12 (government transfers)', 'url' => 'https://www.salmonarm.ca/ArchiveCenter/ViewFile/Item/1286', 'date' => null],
                'bcStats' => ['label' => 'Province of BC: municipal general and financial statistics, Schedules 201 and 401 (2015-2024)', 'url' => 'https://www2.gov.bc.ca/gov/content/governments/local-governments/facts-framework/statistics/statistics', 'date' => null],
                'bcAirFuel2017' => ['label' => 'BC Gov News: Funding supports Salmon Arm Airport infrastructure project', 'url' => 'https://news.gov.bc.ca/releases/2017TRAN0084-000686', 'date' => '2017-03-20'],
                'bcAir2023' => ['label' => 'BC Gov News: B.C. Air Access Program 2023 awards (Salmon Arm, $1.2 million runway)', 'url' => 'https://news.gov.bc.ca/releases/2023MOTI0068-000777', 'date' => '2023-05-19'],
                'bcAir2026' => ['label' => 'BC Gov News: B.C. Air Access Program 2026, 18 airport upgrades', 'url' => 'https://news.gov.bc.ca/releases/2026TT0048-000601', 'date' => null],
                'obsAirport2019' => ['label' => 'Salmon Arm Observer: airport borrowing for the new runway; $520,000 Air Access approval', 'url' => 'https://saobserver.net/2019/10/21/salmon-arm-airport-appreciation-day-plans-underway-borrowing-flies-for-new-runway/', 'date' => '2019-10-21'],
                'obsUnderpass2018' => ['label' => 'Salmon Arm Observer: City proceeds with borrowing for Ross Street underpass', 'url' => 'https://saobserver.net/2018/11/22/city-proceeds-with-borrowing-for-ross-street-underpass/', 'date' => '2018-11-22'],
                'cityWestBay' => ['label' => 'City of Salmon Arm: West Bay Connector Trail', 'url' => 'https://www.salmonarm.ca/475/West-Bay-Connector-Trail', 'date' => null],
                'pwnSigns2023' => ['label' => 'Penticton Western News: new highway signs to welcome people driving into Salmon Arm', 'url' => 'https://pentictonwesternnews.com/2023/12/19/new-highway-signs-to-welcome-people-driving-into-salmon-arm-next-spring/', 'date' => '2023-12-19'],
                'ubcmCcbf2023' => ['label' => 'UBCM: Canada Community-Building Fund in BC, 2023 annual report', 'url' => 'https://www.ubcm.ca/sites/default/files/2024-12/CCBF_BC_2024_Annual_Report_FINAL.pdf', 'date' => '2024-12-01'],
                'vz2025' => ['label' => 'Vision Zero BC: 2025-2026 projects list', 'url' => 'https://cdn.prod.website-files.com/678ef2b34de2f87c67fbbdaa/67f970573dd5008f6429b8ca_Vision%20Zero%20BC%20-%202025-2026%20Projects%20List.pdf', 'date' => null],
                'obsWpcc2026' => ['label' => 'Salmon Arm Observer: $7M contract for sewage plant upgrade design work', 'url' => 'https://saobserver.net/2026/09/25/salmon-arm-looking-at-7m-bill-for-engineering-design-works-for-sewage-plant-upgrade/', 'date' => '2026-09-25'],
                'citySpf2026' => ['label' => 'City of Salmon Arm: Building Communities Strong Fund, $58,000 for a long-term financial plan', 'url' => 'https://www.salmonarm.ca/m/newsflash/Home/Detail/469', 'date' => '2026-08-07'],
                'obsParkHill' => ['label' => 'Salmon Arm Observer: City pursuing grant to upgrade popular but boggy trail', 'url' => 'https://saobserver.net/2026/01/16/city-pursuing-grant-to-upgrade-popular-but-boggy-salmon-arm-trail/', 'date' => '2026-01-16'],
                'evnFifa' => ['label' => 'Eagle Valley News: City of Salmon Arm scores $70K for FIFA celebration', 'url' => 'https://eaglevalleynews.com/2026/04/08/city-of-salmon-arm-scores-70k-for-fifa-celebration/', 'date' => '2026-04-08'],
            ],

            'stats' => [
                ['value' => '63', 'label' => 'grant applications found, 2016-2026', 'sources' => ['agendaCenter', 'escribe']],
                ['value' => '32 of 50', 'label' => 'funded, where the result is known (64%)', 'sources' => ['ar2019', 'fs2025']],
                ['value' => '$8.7M', 'label' => 'won through applications, 2016-2025', 'sources' => ['ar2016', 'fs2025']],
                ['value' => '$179', 'label' => 'per resident a year from other governments; similar towns $254', 'sources' => ['bcStats']],
            ],

            // One row per application council authorized. outcome: funded,
            // not_funded (inferred, see the class comment), no_record, pending,
            // unknown, not_submitted.
            'ledger' => [
                [
                    'year' => 2016,
                    'program' => 'Green Municipal Fund (brownfields)',
                    'project' => 'Airport brownfield assessment, phase II',
                    'asked' => '$75K',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'A provincial brownfield study grant of $45,400 was recorded in 2016 ($12,183 returned in 2017); it may not be from this application.',
                    'sources' => ['agendaCenter', 'ar2016', 'ar2017'],
                ],
                [
                    'year' => 2016,
                    'program' => 'BC Healthy Communities',
                    'project' => 'Leadership capacity building',
                    'asked' => '$15K',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'Council approved the application (0071-2016); no result found.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2016,
                    'program' => 'BC Air Access Program, first intake',
                    'project' => 'Airport fuel system upgrade',
                    'asked' => '$300K project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Submitted again in the second intake the same year.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2016,
                    'program' => 'BC Air Access Program, first intake',
                    'project' => 'Airport Taxiway Charlie',
                    'asked' => '$1.04M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Submitted again in the second intake the same year.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2016,
                    'program' => 'BC Air Access Program, second intake',
                    'project' => 'Airport fuel system upgrade',
                    'asked' => '$300K project',
                    'outcome' => 'funded',
                    'received' => '$225K',
                    'evidence' => 'Announced by the Province in March 2017.',
                    'sources' => ['agendaCenter', 'bcAirFuel2017'],
                ],
                [
                    'year' => 2016,
                    'program' => 'BC Air Access Program, second intake',
                    'project' => 'Airport Taxiway Charlie',
                    'asked' => '$1.04M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Not approved until July 2018.',
                    'sources' => ['agendaCenter', 'obsAirport2019'],
                ],
                [
                    'year' => 2016,
                    'program' => 'Community Energy Leadership Program',
                    'project' => 'Arena cooling system (with the Shuswap Recreation Society)',
                    'asked' => 'Expression of interest',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'No result found.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2016,
                    'program' => 'Clean Water and Wastewater Fund',
                    'project' => 'Zone 5 water booster station',
                    'asked' => '$2.1M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => '$1.74M was budgeted for 2017 and never arrived; the City then sought the money from another fund.',
                    'sources' => ['agendaCenter', 'ar2017'],
                ],
                [
                    'year' => 2016,
                    'program' => 'Clean Water and Wastewater Fund',
                    'project' => 'Sewer capital project',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$1.38M',
                    'evidence' => 'Recorded in the 2017 statements.',
                    'sources' => ['ar2017'],
                ],
                [
                    'year' => 2017,
                    'program' => 'Strategic Priorities Fund (gas tax)',
                    'project' => 'Zone 5 booster station and Ross Street underpass',
                    'asked' => '$12.45M in projects',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'No revenue from this intake; the underpass\'s published funding does not include it.',
                    'sources' => ['agendaCenter', 'obsUnderpass2018'],
                ],
                [
                    'year' => 2017,
                    'program' => 'BC heritage / Canada 150 funding',
                    'project' => 'Art gallery plaza',
                    'asked' => '',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'Council supported the application (0041-2017); no result found.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2018,
                    'program' => 'BC Air Access Program',
                    'project' => 'Airport Taxiway Charlie',
                    'asked' => '$1.37M project',
                    'outcome' => 'funded',
                    'received' => '$520K',
                    'evidence' => 'Approved July 2018.',
                    'sources' => ['obsAirport2019'],
                ],
                [
                    'year' => 2018,
                    'program' => 'Rail Safety Improvement Program (federal)',
                    'project' => 'Ross Street underpass',
                    'asked' => '$424K',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'Reported as "anticipated" in 2018; budgeted in 2019 and 2020 but never recorded as received in the City\'s grant schedule.',
                    'sources' => ['obsUnderpass2018', 'ar2019', 'ar2020'],
                ],
                [
                    'year' => 2019,
                    'program' => 'Investing in Canada Infrastructure (Community, Culture and Recreation)',
                    'project' => 'West Bay Connector Trail',
                    'asked' => '$1.2M project',
                    'outcome' => 'not_submitted',
                    'received' => '',
                    'evidence' => 'Council voted the application down (0523-2018, Jan. 14, 2019).',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2019,
                    'program' => 'UBCM Community Child Care Planning',
                    'project' => 'Child care space plan',
                    'asked' => '$25K',
                    'outcome' => 'funded',
                    'received' => '$25K',
                    'evidence' => 'Recorded in 2019 and 2020.',
                    'sources' => ['agendaCenter', 'ar2019', 'ar2020'],
                ],
                [
                    'year' => 2019,
                    'program' => 'BC Air Access Program 2019',
                    'project' => 'Airport runway paving',
                    'asked' => '$1.5M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Applied again in December 2019 and in 2022; the runway was funded only in 2023.',
                    'sources' => ['agendaCenter', 'bcAir2023'],
                ],
                [
                    'year' => 2019,
                    'program' => 'National Trade Corridors Fund (federal)',
                    'project' => 'Ross Street underpass',
                    'asked' => '$12.4M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Not among the underpass\'s published funding sources.',
                    'sources' => ['agendaCenter', 'obsUnderpass2018'],
                ],
                [
                    'year' => 2019,
                    'program' => 'BC Rural Dividend',
                    'project' => 'West Bay trail planning and design',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$100K',
                    'evidence' => 'Listed on the City\'s trail page; recorded in 2024.',
                    'sources' => ['agendaCenter', 'cityWestBay', 'fs2024'],
                ],
                [
                    'year' => 2019,
                    'program' => 'UBCM Poverty Reduction, stream 1',
                    'project' => 'Poverty reduction plan',
                    'asked' => '$25K',
                    'outcome' => 'funded',
                    'received' => '$25K',
                    'evidence' => 'Recorded in 2021.',
                    'sources' => ['agendaCenter', 'ar2021'],
                ],
                [
                    'year' => 2019,
                    'program' => 'BC Air Access Program 2020-21',
                    'project' => 'Airport runway paving',
                    'asked' => '$1.5M project',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Applied again in 2022; funded only in 2023.',
                    'sources' => ['agendaCenter', 'bcAir2023'],
                ],
                [
                    'year' => 2019,
                    'program' => 'Food hub funding (provincial)',
                    'project' => 'Food hub feasibility and start-up',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$614K',
                    'evidence' => '$49K feasibility (2019-20) and $565K (2020-21).',
                    'sources' => ['ar2019', 'ar2020', 'ar2021'],
                ],
                [
                    'year' => 2019,
                    'program' => 'Infrastructure planning grant',
                    'project' => 'Water infrastructure planning',
                    'asked' => '$10K',
                    'outcome' => 'funded',
                    'received' => '$10K',
                    'evidence' => 'Recorded in 2021.',
                    'sources' => ['ar2021'],
                ],
                [
                    'year' => 2020,
                    'program' => 'BC Active Transportation Infrastructure',
                    'project' => 'Ross Street underpass',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$1.0M',
                    'evidence' => 'Recorded in 2021 and 2022.',
                    'sources' => ['agendaCenter', 'ar2021', 'ar2022'],
                ],
                [
                    'year' => 2020,
                    'program' => 'UBCM Community Emergency Preparedness Fund',
                    'project' => 'Evacuation route planning',
                    'asked' => '',
                    'outcome' => 'no_record',
                    'received' => '',
                    'evidence' => 'No money from this fund recorded until 2024.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2020,
                    'program' => 'FCM Municipal Asset Management Program',
                    'project' => 'Asset management program',
                    'asked' => '$50K project',
                    'outcome' => 'funded',
                    'received' => '$40K',
                    'evidence' => 'Council noted the "successful application" in April 2021.',
                    'sources' => ['agendaCenter', 'ar2021'],
                ],
                [
                    'year' => 2020,
                    'program' => 'FCM Green Municipal Fund',
                    'project' => 'West Bay trail, phase I study and design',
                    'asked' => 'Half of $270K',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'The City\'s trail page lists the design funders, and FCM is not among them.',
                    'sources' => ['agendaCenter', 'cityWestBay'],
                ],
                [
                    'year' => 2020,
                    'program' => 'Community Economic Recovery Infrastructure Program',
                    'project' => 'Park and walkway lighting',
                    'asked' => '$265K',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Budgeted for 2021 and never received.',
                    'sources' => ['agendaCenter', 'ar2021', 'ar2022'],
                ],
                [
                    'year' => 2020,
                    'program' => 'Community Economic Recovery Infrastructure Program',
                    'project' => '13 Avenue industrial park',
                    'asked' => '$985K',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Budgeted for 2021 and never received.',
                    'sources' => ['agendaCenter', 'ar2021', 'ar2022'],
                ],
                [
                    'year' => 2020,
                    'program' => 'Community Economic Recovery Infrastructure Program (with SAEDS)',
                    'project' => 'Destination signage',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => 'Paid to SAEDS',
                    'evidence' => 'The grant went to the Salmon Arm Economic Development Society and largely paid for the entrance signs.',
                    'sources' => ['agendaCenter', 'pwnSigns2023'],
                ],
                [
                    'year' => 2020,
                    'program' => 'ICBC crosswalk safety',
                    'project' => 'Crosswalk improvements',
                    'asked' => '$15K',
                    'outcome' => 'funded',
                    'received' => '$15K',
                    'evidence' => 'Recorded in 2020.',
                    'sources' => ['ar2020'],
                ],
                [
                    'year' => 2021,
                    'program' => 'BC Active Transportation Planning',
                    'project' => 'Active transportation network plan',
                    'asked' => '$50K',
                    'outcome' => 'funded',
                    'received' => '$50K',
                    'evidence' => 'Recorded in 2022.',
                    'sources' => ['agendaCenter', 'ar2022'],
                ],
                [
                    'year' => 2021,
                    'program' => 'Canada Community Revitalization Fund',
                    'project' => 'Ross Street plaza washroom',
                    'asked' => '$84K',
                    'outcome' => 'funded',
                    'received' => '$84K',
                    'evidence' => 'Recorded in 2023 and 2024.',
                    'sources' => ['agendaCenter', 'fs2023', 'fs2024'],
                ],
                [
                    'year' => 2021,
                    'program' => 'Building Safer Communities Fund (federal)',
                    'project' => 'Youth gang and gun violence prevention',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$753K',
                    'evidence' => 'Recorded 2022-2025.',
                    'sources' => ['ar2022', 'fs2023', 'fs2024', 'fs2025'],
                ],
                [
                    'year' => 2022,
                    'program' => 'UBCM Poverty Reduction, stream 2',
                    'project' => 'Anti-stigma campaign',
                    'asked' => '$50K',
                    'outcome' => 'funded',
                    'received' => '$50K',
                    'evidence' => 'Recorded in 2022 and 2023.',
                    'sources' => ['agendaCenter', 'fs2023'],
                ],
                [
                    'year' => 2022,
                    'program' => 'Active Transportation Fund (federal)',
                    'project' => '16 Avenue NE multi-use path',
                    'asked' => '',
                    'outcome' => 'no_record',
                    'received' => '',
                    'evidence' => 'No federal money from this fund recorded; the City\'s share was moved to another project in 2023.',
                    'sources' => ['agendaCenter', 'escribe'],
                ],
                [
                    'year' => 2022,
                    'program' => 'CleanBC Communities Fund',
                    'project' => 'Shaw Centre heating and air units',
                    'asked' => '$422.5K project',
                    'outcome' => 'funded',
                    'received' => '$337K',
                    'evidence' => 'Recorded in 2024 and 2025.',
                    'sources' => ['agendaCenter', 'fs2024', 'fs2025'],
                ],
                [
                    'year' => 2022,
                    'program' => 'UBCM FireSmart (2022)',
                    'project' => 'FireSmart program',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$7K',
                    'evidence' => 'Recorded in 2022.',
                    'sources' => ['agendaCenter', 'ar2022'],
                ],
                [
                    'year' => 2022,
                    'program' => 'Strategic Priorities Fund 2022 (gas tax)',
                    'project' => 'Foreshore water main phase 2 and transportation master plan',
                    'asked' => '$1.7M',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'No money from this fund recorded 2022-2025; only 45 projects were approved province-wide.',
                    'sources' => ['agendaCenter', 'ubcmCcbf2023'],
                ],
                [
                    'year' => 2022,
                    'program' => 'BC Active Transportation Infrastructure',
                    'project' => 'Ross Street underpass, phase 2',
                    'asked' => '$500K',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'The next award from this program (2024) was for a different project.',
                    'sources' => ['agendaCenter', 'fs2024'],
                ],
                [
                    'year' => 2022,
                    'program' => 'UBCM FireSmart (2023)',
                    'project' => 'FireSmart program',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$100K',
                    'evidence' => 'Recorded in 2023 and 2024.',
                    'sources' => ['agendaCenter', 'fs2023', 'fs2024'],
                ],
                [
                    'year' => 2022,
                    'program' => 'BC Air Access Program 2022-23',
                    'project' => 'Airport runway repaving',
                    'asked' => '$1.65M project',
                    'outcome' => 'funded',
                    'received' => '$1.24M',
                    'evidence' => 'Announced by the Province in 2023.',
                    'sources' => ['agendaCenter', 'bcAir2023'],
                ],
                [
                    'year' => 2022,
                    'program' => 'Destination Development Fund (expression of interest)',
                    'project' => 'Canoe Beach reinstatement',
                    'asked' => '$500K project',
                    'outcome' => 'no_record',
                    'received' => '',
                    'evidence' => 'No award found.',
                    'sources' => ['agendaCenter'],
                ],
                [
                    'year' => 2022,
                    'program' => 'ICBC Road Improvement Program',
                    'project' => 'Road safety improvements',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$119K',
                    'evidence' => 'Recorded in 2022 and 2023.',
                    'sources' => ['ar2022', 'fs2023'],
                ],
                [
                    'year' => 2023,
                    'program' => 'UBCM Complete Communities',
                    'project' => 'Complete communities study',
                    'asked' => '$150K',
                    'outcome' => 'funded',
                    'received' => '$150K',
                    'evidence' => 'Recorded in 2023 and 2024.',
                    'sources' => ['agendaCenter', 'fs2023', 'fs2024'],
                ],
                [
                    'year' => 2023,
                    'program' => 'BC Active Transportation Infrastructure',
                    'project' => 'Downtown-to-uptown connector',
                    'asked' => '$411K',
                    'outcome' => 'funded',
                    'received' => '$411K',
                    'evidence' => 'Recorded in 2024.',
                    'sources' => ['escribe', 'fs2024'],
                ],
                [
                    'year' => 2023,
                    'program' => 'UBCM Emergency Preparedness (fire departments)',
                    'project' => 'Equipment and training',
                    'asked' => '$29K',
                    'outcome' => 'funded',
                    'received' => '$28K',
                    'evidence' => 'Recorded in 2024.',
                    'sources' => ['escribe', 'fs2024'],
                ],
                [
                    'year' => 2024,
                    'program' => 'UBCM Disaster Risk Reduction - Climate Adaptation',
                    'project' => 'Climate risk assessment and resilience plan',
                    'asked' => '$150K',
                    'outcome' => 'funded',
                    'received' => '$150K',
                    'evidence' => 'Recorded in 2025.',
                    'sources' => ['escribe', 'fs2025'],
                ],
                [
                    'year' => 2024,
                    'program' => 'PlanH (BC Healthy Communities)',
                    'project' => 'Anti-racism strategy, phase 1',
                    'asked' => '$15K',
                    'outcome' => 'funded',
                    'received' => '$15K',
                    'evidence' => 'Recorded in 2024 and 2025.',
                    'sources' => ['escribe', 'fs2024', 'fs2025'],
                ],
                [
                    'year' => 2024,
                    'program' => 'Public Health Agency of Canada, Intersectoral Action Fund',
                    'project' => 'Food and urban agriculture plan',
                    'asked' => '$100K',
                    'outcome' => 'no_record',
                    'received' => '',
                    'evidence' => 'No money from this fund recorded in 2024 or 2025.',
                    'sources' => ['escribe', 'fs2025'],
                ],
                [
                    'year' => 2024,
                    'program' => 'UBCM Emergency Preparedness (fire departments)',
                    'project' => 'Equipment and training',
                    'asked' => '$40K',
                    'outcome' => 'funded',
                    'received' => '$35K',
                    'evidence' => 'Recorded in 2025.',
                    'sources' => ['escribe', 'fs2025'],
                ],
                [
                    'year' => 2024,
                    'program' => 'Vision Zero road safety grant',
                    'project' => '21 Street NE mid-block crossing',
                    'asked' => '',
                    'outcome' => 'funded',
                    'received' => '$17.5K',
                    'evidence' => 'On the program\'s 2025-26 project list.',
                    'sources' => ['escribe', 'vz2025'],
                ],
                [
                    'year' => 2024,
                    'program' => 'UBCM FireSmart (2025)',
                    'project' => 'FireSmart program',
                    'asked' => '$400K',
                    'outcome' => 'funded',
                    'received' => '$236K',
                    'evidence' => '$236K recorded in 2025.',
                    'sources' => ['escribe', 'fs2025'],
                ],
                [
                    'year' => 2025,
                    'program' => 'PlanH (BC Healthy Communities)',
                    'project' => 'Anti-racism strategy, phase 2',
                    'asked' => '$15K',
                    'outcome' => 'funded',
                    'received' => '$15K',
                    'evidence' => 'Recorded in 2025.',
                    'sources' => ['escribe', 'fs2025'],
                ],
                [
                    'year' => 2025,
                    'program' => 'UBCM Community to Community (joint)',
                    'project' => 'Joint application with Adams Lake and Neskonlith',
                    'asked' => '',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'No result found.',
                    'sources' => ['escribe'],
                ],
                [
                    'year' => 2025,
                    'program' => 'Building Communities Strong Fund (Strategic Priorities)',
                    'project' => 'Sewage treatment plant (WPCC Stage IV) upgrade',
                    'asked' => '$7M',
                    'outcome' => 'pending',
                    'received' => '',
                    'evidence' => 'In September 2026 the City was told the project would be "a strong contender".',
                    'sources' => ['escribe', 'obsWpcc2026'],
                ],
                [
                    'year' => 2025,
                    'program' => 'Building Communities Strong Fund (Strategic Priorities)',
                    'project' => 'Long-term financial plan for asset management',
                    'asked' => '$58K',
                    'outcome' => 'funded',
                    'received' => '$58K',
                    'evidence' => 'Announced July 30, 2026.',
                    'sources' => ['escribe', 'citySpf2026'],
                ],
                [
                    'year' => 2025,
                    'program' => 'UBCM Emergency Preparedness (fire departments)',
                    'project' => 'Equipment and training',
                    'asked' => '$30K',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'No result found yet.',
                    'sources' => ['escribe'],
                ],
                [
                    'year' => 2025,
                    'program' => 'Vision Zero road safety grant',
                    'project' => '2026 intake',
                    'asked' => '',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'No result found yet.',
                    'sources' => ['escribe'],
                ],
                [
                    'year' => 2025,
                    'program' => 'BC Air Access Program 2026-27',
                    'project' => 'Airport helipad rehabilitation',
                    'asked' => '$60K',
                    'outcome' => 'not_funded',
                    'received' => '',
                    'evidence' => 'Not among the 18 projects the Province announced in 2026.',
                    'sources' => ['escribe', 'bcAir2026'],
                ],
                [
                    'year' => 2026,
                    'program' => 'Outdoor Recreation Council of BC',
                    'project' => 'Park Hill Outer Loop trail',
                    'asked' => '$10K',
                    'outcome' => 'unknown',
                    'received' => '',
                    'evidence' => 'No result found yet.',
                    'sources' => ['escribe', 'obsParkHill'],
                ],
                [
                    'year' => 2026,
                    'program' => 'Community Event Support Fund',
                    'project' => 'FIFA World Cup viewing party',
                    'asked' => '$75K',
                    'outcome' => 'funded',
                    'received' => '$70.5K',
                    'evidence' => 'Announced April 8, 2026.',
                    'sources' => ['escribe', 'evnFifa'],
                ],
                [
                    'year' => 2026,
                    'program' => 'PlanH (BC Healthy Communities)',
                    'project' => 'Anti-racism strategy, phase 3',
                    'asked' => '$15K',
                    'outcome' => 'pending',
                    'received' => '',
                    'evidence' => 'Submitted in 2026.',
                    'sources' => ['escribe'],
                ],
                [
                    'year' => 2026,
                    'program' => 'Rail Safety Improvement Program (federal)',
                    'project' => 'CPKC active transportation crossing',
                    'asked' => '$336K',
                    'outcome' => 'pending',
                    'received' => '',
                    'evidence' => 'Submitted in 2026.',
                    'sources' => ['escribe'],
                ],
            ],

            // Known results by the year council authorized the application.
            'eras' => [
                [
                    'label' => '2016–2019',
                    'decided' => 16,
                    'funded' => 8,
                ],
                [
                    'label' => '2020–2022',
                    'decided' => 21,
                    'funded' => 13,
                ],
                [
                    'label' => '2023–2026',
                    'decided' => 13,
                    'funded' => 11,
                ],
            ],

            // Grant money by year from the audited grant schedules: formula money
            // (gas tax Community Works Fund, COVID restart, Growing Communities,
            // small-community and traffic-fine sharing, climate and housing
            // allocations, hotel tax) vs grants the City applied for. Grants in
            // lieu of taxes and a partner contribution are left out.
            'years' => [
                [
                    'year' => 2016,
                    'formula' => 1626858,
                    'applied' => 45400,
                ],
                [
                    'year' => 2017,
                    'formula' => 811804,
                    'applied' => 1363317,
                ],
                [
                    'year' => 2018,
                    'formula' => 1190733,
                    'applied' => 803245,
                ],
                [
                    'year' => 2019,
                    'formula' => 1595950,
                    'applied' => 121390,
                ],
                [
                    'year' => 2020,
                    'formula' => 4507162,
                    'applied' => 582435,
                ],
                [
                    'year' => 2021,
                    'formula' => 711887,
                    'applied' => 945642,
                ],
                [
                    'year' => 2022,
                    'formula' => 6433911,
                    'applied' => 631569,
                ],
                [
                    'year' => 2023,
                    'formula' => 7786701,
                    'applied' => 1696521,
                ],
                [
                    'year' => 2024,
                    'formula' => 2330428,
                    'applied' => 1194406,
                ],
                [
                    'year' => 2025,
                    'formula' => 1676213,
                    'applied' => 1362694,
                ],
            ],

            // Money from other governments per resident a year (2021 census),
            // 2015-2024 and its two halves: stand-alone towns of 12,000-32,000
            // without special funding arrangements, highest first.
            'peers' => [
                [
                    'name' => 'Powell River',
                    'population' => 13943,
                    'per_resident' => 724,
                    'early' => 220,
                    'late' => 1229,
                ],
                [
                    'name' => 'Summerland',
                    'population' => 12042,
                    'per_resident' => 401,
                    'early' => 285,
                    'late' => 517,
                ],
                [
                    'name' => 'Port Alberni',
                    'population' => 18259,
                    'per_resident' => 369,
                    'early' => 332,
                    'late' => 406,
                ],
                [
                    'name' => 'Parksville',
                    'population' => 13642,
                    'per_resident' => 293,
                    'early' => 288,
                    'late' => 298,
                ],
                [
                    'name' => 'Lake Country',
                    'population' => 15817,
                    'per_resident' => 275,
                    'early' => 206,
                    'late' => 344,
                ],
                [
                    'name' => 'Squamish',
                    'population' => 23819,
                    'per_resident' => 254,
                    'early' => 167,
                    'late' => 342,
                ],
                [
                    'name' => 'Cranbrook',
                    'population' => 20499,
                    'per_resident' => 247,
                    'early' => 147,
                    'late' => 347,
                ],
                [
                    'name' => 'Comox',
                    'population' => 14806,
                    'per_resident' => 228,
                    'early' => 119,
                    'late' => 337,
                ],
                [
                    'name' => 'Courtenay',
                    'population' => 28420,
                    'per_resident' => 191,
                    'early' => 132,
                    'late' => 250,
                ],
                [
                    'name' => 'Salmon Arm',
                    'population' => 19432,
                    'per_resident' => 179,
                    'early' => 87,
                    'late' => 271,
                ],
                [
                    'name' => 'North Cowichan',
                    'population' => 31990,
                    'per_resident' => 159,
                    'early' => 107,
                    'late' => 211,
                ],
            ],
            'groups' => [
                [
                    'label' => 'All 26 BC municipalities of 12,000-32,000 people',
                    'median' => 242,
                    'rank' => 21,
                    'of' => 26,
                ],
                [
                    'label' => 'Leaving out the six with special funding arrangements',
                    'median' => 220,
                    'rank' => 15,
                    'of' => 20,
                ],
                [
                    'label' => 'Stand-alone towns only (the closest match)',
                    'median' => 254,
                    'rank' => 10,
                    'of' => 11,
                ],
            ],
            'halves' => [
                'early' => [
                    'salmon_arm' => 87,
                    'median' => 167,
                ],
                'late' => [
                    'salmon_arm' => 271,
                    'median' => 342,
                ],
            ],
            'excluded' => [
                [
                    'name' => 'Dawson Creek',
                    'reason' => 'Peace River Agreement (resource revenue sharing)',
                ],
                [
                    'name' => 'Fort St. John',
                    'reason' => 'Peace River Agreement (resource revenue sharing)',
                ],
                [
                    'name' => 'Whistler',
                    'reason' => 'Resort municipality funding',
                ],
                [
                    'name' => 'Prince Rupert',
                    'reason' => 'Northwest resource benefits agreement and port payments',
                ],
                [
                    'name' => 'Terrace',
                    'reason' => 'Northwest resource benefits agreement',
                ],
                [
                    'name' => 'Langley',
                    'reason' => 'Metro Vancouver city',
                ],
            ],

            'analysis' => [
                ['heading' => 'Small grants usually come through; big ones rarely have', 'text' => 'Most applications for planning studies, emergency preparedness, FireSmart and active transportation were funded. Of the applications for projects of $1 million or more, most failed: the Ross Street underpass under two programs, the Zone 5 booster station twice, the runway twice before it succeeded, and the 2020 recovery-fund projects. The largest single grant the City has won since 2016 is about $1.4 million.', 'sources' => ['agendaCenter', 'ar2017', 'bcAir2023']],
                ['heading' => 'Less outside money than similar towns, but the gap is closing', 'text' => 'Over 2015-2024 Salmon Arm took in $179 per resident a year from other governments, against a median of $254 for comparable stand-alone towns, ranking 10th of 11. In 2015-2019 it was about half the median; in 2020-2024 about 79%. These totals include formula money every town receives, so the gap comes mostly from grants won by applying.', 'sources' => ['bcStats']],
                ['heading' => 'Formula money does most of the work', 'text' => 'Of the $37.4 million in grants recorded 2016-2025, $28.7 million arrived by formula (mainly the federal gas tax share, the COVID-19 restart grant and the Growing Communities Fund) and $8.7 million came from applications.', 'sources' => ['ar2016', 'fs2025']],
                ['heading' => 'The sewage plant is the next test', 'text' => 'The City has asked for $7 million toward a sewage plant upgrade now estimated at about $100 million, and was told in September 2026 it would be "a strong contender". Every dollar of grant is a dollar not borrowed: borrowed over 30 years at today\'s rate, $7 million would cost about $432,000 a year, close to 2% of City property taxes.', 'sources' => ['obsWpcc2026', 'escribe']],
            ],

            'questions' => [
                'What would you do to win large capital grants, starting with the sewage plant?',
                'Should the City keep designs "shovel-ready" so it can apply as soon as federal and provincial programs open?',
                'Does the City have enough staff time for grant writing, or should it pay for more?',
            ],

            'method' => [
                'Applications are the ones council authorized by resolution. Some small applications are made by staff without a resolution, so the count is a minimum.',
                '"Not funded" is inferred from public evidence: the City applied again for the same project, a budgeted grant never arrived, or the project\'s published funding left it out. Funders seldom announce who was turned down.',
                'Money is counted when the City records it, often a year or more after the award, because grants are recognized as they are spent.',
                'The peer comparison uses the Province\'s figures for money from federal, provincial and other governments, which mix formula money with competitive grants. Other towns\' application success rates are not published, so only dollars can be compared.',
                'Joint wildfire applications led by the Neskonlith Indian Band (2018-2021) are not counted: the band applied and received the money.',
            ],

            'gaps' => [
                'Some 2016-2018 minutes are only available inside agenda packages; a meeting missing from those packages would also be missing here.',
            ],
        ];
    }
}
